apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: twschallengeacrvishal.azurecr.io/tws_3tier_challenge_frontend:v1
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://app.20.207.122.241.nip.io/api/tasks" 
        ports:
        - containerPort: 3000
       
